"""
Django settings for {{ cookiecutter.project_slug }} project.

Generated by 'django-admin startproject' using Django {{ cookiecutter.django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from modules.secrets import secret_manager

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_manager.get_secret('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = secret_manager.get_secret('DEBUG')

# Platform
import CONFIG.platform as platform_config
import CONFIG.billing as billing_config
PLATFORM_NAME = platform_config.PLATFORM_NAME
PLATFORM_TAGLINE = platform_config.PLATFORM_TAGLINE
PLATFORM_VERSION = platform_config.PLATFORM_VERSION
PLATFORM_URL = platform_config.PLATFORM_URL
BILLING_MODEL = billing_config.BILLING_MODEL

# Allowed hosts
ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://127.0.0.1', PLATFORM_URL]

# Application definition
PLATFORM_APPS = [
    '{{ cookiecutter.main_app_name }}'
]

INSTALLED_APPS = PLATFORM_APPS + [

    # Third-party apps that should come before Ship with Django apps
    'unfold', # Admin panel with Tailwind CSS
    'daphne', # ASGI server
    'huey.contrib.djhuey', # Huey task queue
    'channels', # Websockets
    'tailwind', # Tailwind CSS
    'theme', # Custom Tailwind CSS theme
    'django_browser_reload', # Browser reload for development
    'rest_framework', # API
    'rest_framework_simplejwt', # JWT authentication
    'rest_framework_simplejwt.token_blacklist', # Blacklist tokens
    'impersonate', # Impersonate users

    # Ship with Django apps
    'modules',
    'modules.authentication',
    'modules.billing',
    'modules.payments',
    'modules.emails',
    'modules.utils',

    'modules.examples', # Remove this line if you don't want the examples

    # Third-party apps that should come after Ship with Django apps
    'rosetta', # Translations

    # Django apps
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Social authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.mfa',

    # This should be at the end of the list
    'modules.admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'impersonate.middleware.ImpersonateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = '{{ cookiecutter.project_slug }}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'modules.context_processors.add_global_subnav',
                'modules.context_processors.add_platform_config'
            ],
        },
    },
]

WSGI_APPLICATION = '{{ cookiecutter.project_slug }}.wsgi.application'
ASGI_APPLICATION = '{{ cookiecutter.project_slug }}.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': secret_manager.get_secret('DB_NAME'),
        'USER': secret_manager.get_secret('DB_USER'),
        'PASSWORD': secret_manager.get_secret('DB_PASSWORD'),
        'HOST': secret_manager.get_secret('DB_HOST'),
        'PORT' : secret_manager.get_secret('DB_PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
import CONFIG.translations as translations_config
LANGUAGE_CODE = ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = translations_config.SOURCE_LANGUAGE_CODE
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = translations_config.SOURCE_LANGUAGE_NAME
ROSETTA_MESSAGES_PER_PAGE = translations_config.ROSETTA_MESSAGES_PER_PAGE
ROSETTA_ENABLE_REFLANG = True

AZURE_CLIENT_SECRET = translations_config.AZURE_CLIENT_SECRET # Used for Azure translation service
YANDEX_TRANSLATE_KEY = translations_config.YANDEX_TRANSLATE_KEY # Used for Yandex translation service
DEEPL_AUTH_KEY = translations_config.DEEPL_AUTH_KEY # Used for DeepL translation service

LANGUAGES = translations_config.LANGUAGES
ROSSETA_LANGUAGES = translations_config.ROSETTA_LANGUAGES + LANGUAGES

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media content
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Huey (Task queue) config
import CONFIG.task_queue as task_queue_config
HUEY = {
    'huey_class' : task_queue_config.HUEY_CLASS,
    'results' : True,
    'store_none' : False,
    'immediate' : False,
    'connection' : {
        'host' : task_queue_config.REDIS_HOST,
        'port' : task_queue_config.REDIS_PORT,
        'db' : 0,
        'connection_pool' : None,
        'read_timeout' : None,
        'url' : None,
    },
}

# Authentication
import CONFIG.authentication as authentication_config
SITE_ID = 1
AUTH_USER_MODEL = '{{ cookiecutter.main_app_name }}.User'
LOGIN_URL = 'authentication:login'
LOGIN_REDIRECT_URL = '{{ cookiecutter.main_app_name }}:dashboard'
LOGOUT_REDIRECT_URL = 'authentication:login'
ALLOW_THIRD_PARTY_LOGIN = authentication_config.ALLOW_THIRD_PARTY_LOGIN
ALLOW_GITHUB_LOGIN = authentication_config.ALLOW_GITHUB_LOGIN
ALLOW_LINKED_IN_LOGIN = authentication_config.ALLOW_LINKED_IN_LOGIN
ALLOW_REGISTRATIONS = authentication_config.ALLOW_REGISTRATIONS

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {}

if ALLOW_LINKED_IN_LOGIN and ALLOW_THIRD_PARTY_LOGIN:
    SOCIALACCOUNT_PROVIDERS['openid_connect'] = {
        "APPS": [
            {
                "provider_id": "linkedin",
                "name": "LinkedIn",
                "client_id": authentication_config.LINKED_IN_CLIENT_ID,
                "secret": authentication_config.LINKED_IN_CLIENT_SECRET,
                "settings": {
                    "server_url": "https://www.linkedin.com/oauth",
                },
            }
        ]
    }

if ALLOW_GITHUB_LOGIN and ALLOW_THIRD_PARTY_LOGIN:
    SOCIALACCOUNT_PROVIDERS['github'] = {
        'APP': {
            'client_id': authentication_config.GITHUB_CLIENT_ID,
            'secret': authentication_config.GITHUB_CLIENT_SECRET,
            'key': ''
        },
        'VERIFIED_EMAIL': True
    }   

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Logging
import CONFIG.logging as logging_config

if logging_config.USE_SENTRY:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=logging_config.SENTRY_DSN,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
        send_default_pii=True,
        integrations=[
        DjangoIntegration(
            transaction_style='url',
            middleware_spans=True,
            cache_spans=False,
        ),
        ],
    )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamp': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'logfile': {
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': f'./logs/{logging_config.LOGFILE_PATH}',
            'formatter' : 'timestamp',
            'level' : 'ERROR'
        },
        'console' : {
            'class' : 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django': {
            'handlers': ['logfile', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

if logging_config.USE_BETTERSTACK:
    LOGGING['handlers']['logtail'] = {
        'class': 'logtail.LogtailHandler',
        'source_token': logging_config.BETTERSTACK_SOURCE_TOKEN,
    }
    LOGGING['loggers']['logtail'] = {
        'handlers': ['logtail'],
        'level': 'INFO',
        'propagate': False,
    }

# Default email settings
import CONFIG.emails as email_config
EMAIL_PROVIDER = email_config.EMAIL_PROVIDER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = email_config.EMAIL_HOST
EMAIL_PORT = email_config.EMAIL_PORT
EMAIL_HOST_USER = email_config.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = email_config.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = email_config.EMAIL_USE_TLS
EMAIL_USE_TASK_QUEUE = email_config.EMAIL_USE_TASK_QUEUE
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SENDGRID_API_KEY = email_config.SENDGRID_API_KEY


# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(secret_manager.get_secret('REDIS_HOST'), 6379)],
        },
    },
}

# Tailwind
TAILWIND_APP_NAME = 'theme'

# Forms
FORM_RENDERER = 'modules.forms.FormRenderer'

# Stripe
import CONFIG.stripe as stripe_config
STRIPE_LIVE_MODE = stripe_config.STRIPE_LIVE_MODE
STRIPE_SECRET_KEY = stripe_config.STRIPE_TEST_SECRET_KEY if not STRIPE_LIVE_MODE else stripe_config.STRIPE_LIVE_SECRET_KEY
STRIPE_WEBHOOK_SECRET = stripe_config.STRIPE_TEST_WEBHOOK_SECRET if not STRIPE_LIVE_MODE else stripe_config.STRIPE_LIVE_WEBHOOK_SECRET

# Unfold (Django Admin Panel)
UNFOLD = {
    'SITE_TITLE' : platform_config.PLATFORM_NAME,
    'SITE_HEADER' : platform_config.PLATFORM_NAME,
    'SITE_SYMBOL' : 'rocket_launch',
    "SIDEBAR" : {
        'show_search' : True,
        'show_all_applications' : True,
        "navigation": [
            {
                "title": "",
                "items": [
                    {
                        "title" : _('Back to site'),
                        "icon" : 'arrow_back',
                        "link" : '/dashboard',
                    },
                ],
            },
            {
                "title": _("Navigation"),
                "separator": True,  # Top border
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:{{ cookiecutter.main_app_name }}_user_changelist"),
                    },
                    {
                        "title": _("Translations"),
                        "icon": "translate",
                        "link": reverse_lazy("rosetta-old-home-redirect"),
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "primary": {
            "50": "240 243 254",
            "100": "222 228 251",
            "200": "196 208 249",
            "300": "156 178 244",
            "400": "108 137 238",
            "500": "75 100 231",
            "600": "53 69 219",
            "700": "44 51 201",
            "800": "42 43 163",
            "900": "39 42 129",
            "950": "28 29 79",
        },
    },
}

# REST Framework (API)
import CONFIG.api as api_config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication', # JWT authentication
    ],
}

SIMPLE_JWT = {
    "SIGNING_KEY" : api_config.SIGNING_KEY, # Secret key for JWT
    "ACCESS_TOKEN_LIFETIME" : timedelta(minutes=api_config.ACCESS_TOKEN_EXPIRE_MINUTES),
    "REFRESH_TOKEN_LIFETIME" : timedelta(days=api_config.REFRESH_TOKEN_EXPIRES_DAYS),
    "ROTATE_REFRESH_TOKENS" : True, # Rotate refresh tokens when refreshing - this will add a new refresh token when asking for a new access token
    "BLACKLIST_AFTER_ROTATION" : True, # Blacklist old refresh tokens when rotating
    "UPDATE_LAST_LOGIN" : False # Don't update last login user field when using JWT - this may cause abuse (see https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#update-last-login)
}

# Impersonation
IMPERSONATE = {
    'USE_HTTP_REFERER' : True,
}

# OpenAI
import CONFIG.openai as openai_config
OPENAI_API_KEY = openai_config.OPENAI_API_KEY