# Generated by Django 5.0.2 on 2024-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('credits_before', models.IntegerField()),
                ('credits_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('hosted_invoice_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_key', models.CharField(max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_status', models.CharField(blank=True, max_length=255, null=True)),
                ('starts', models.BigIntegerField(default=0)),
                ('current_period_start', models.BigIntegerField(default=0)),
                ('current_period_end', models.BigIntegerField(default=0)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('lifetime', models.BooleanField(default=False)),
            ],
        ),
    ]
